add /visit GET and POST routes to user api
ct-fiuba/ct-user-api pull request #5
Opened 2020-11-01 22:02 UTC by tomasaccini

Actualizo con los ultimos cambios del visit manager

@ct-fiuba/developers

2020-11-02 16:22 UTC, NachoRaik requested changes
Re pio x2, un par de cosillas nomas

2020-11-02 16:22 UTC, NachoRaik commented on src/middlewares/genuxMiddleware.js
> +};
Solo para evitar agregar otro file, y dado que ya tiene relacion, lo tendria en el middleware de `auth` (agregado como otra funcion).

2020-11-02 16:22 UTC, NachoRaik commented on src/middlewares/genuxMiddleware.js
> +      json: { genuxToken: req.body.genuxToken }
A la user API no le llegaba en un header? Y despues si se mandaba en el body al Auth Server.

2020-11-03 01:28 UTC, tomasaccini commented on src/middlewares/genuxMiddleware.js
> +      json: { genuxToken: req.body.genuxToken }
No me acuerdo en qué había quedado, el access token lo esta recibiendo por un header ahora. @olifer97 que opinás?

2020-11-03 01:34 UTC, tomasaccini commented
Una cosa importante que me olvide de comentar, el endpoint de GET /visit lo va a usar el worker para obtener todas las visitas y buscar contagios, entonces no tiene ni la validación del access token ni del genux token. Voy a agregar un issue extra para que agreguemos seguridad de que únicamente este worker pueda pegarle. Después seguramente tengamos más endpoints que únicamente sistemas internos van a poder usar (marcar visitas como con peligro de contagio, armar la cartelera de visitas con riesgo, etc)

2020-11-03 12:42 UTC, olifer97 approved these changes
TODO COOOOL. solo sacar el get je

2020-11-03 12:42 UTC, olifer97 commented on src/middlewares/genuxMiddleware.js
> +      json: { genuxToken: req.body.genuxToken }
No entendi, osea la idea es q la app mande ambos tokens por header?

2020-11-05 02:56 UTC, tomasaccini commented on src/middlewares/genuxMiddleware.js
> +      json: { genuxToken: req.body.genuxToken }
Ahí hice que la user api reciba por header los tokens, pero despues le pega al visit manager con el genux token en el body

2020-11-05 18:25 UTC, olifer97 reviewed
solo unos coments por el cambio de body a header del genuxToken

2020-11-05 18:25 UTC, olifer97 commented on src/static/swagger.json
> +          "genuxToken"
habria q mover en el swagger el genuxToken al header 😅

2020-11-05 18:25 UTC, olifer97 commented on test/integration/app.int.test.js
> +          genuxToken: validGenuxToken
esto aca ya no hace falta no?

2020-11-06 00:46 UTC, NachoRaik approved these changes

2020-11-06 00:46 UTC, NachoRaik commented on src/routes/visitsRouter.js
> +      .post('/', genuxMiddleware(), visitsController.add)
Es una re boludez esto, pero me perturba apenitas la invocacion aca (porque en realidad `genuxMiddleware` devuelve la funcion en lugar de ser la funcion indeed). 
Igual es super minimo, ni lo cambies, pero queria expresarlo 🐦

2020-11-06 01:23 UTC, tomasaccini commented on src/routes/visitsRouter.js
> +      .post('/', genuxMiddleware(), visitsController.add)
Sisi totalmente, no encontré la forma de hacer que genuxMiddleware sea la función en sí, probe un par de cosas sobre cómo exportarlo y como importarlo pero sin suerte. Tienen idea como hacerlo?

2020-11-06 01:25 UTC, tomasaccini commented on src/routes/visitsRouter.js
> +      .post('/', genuxMiddleware(), visitsController.add)
No dije nada ahí pude :)

2020-11-06 01:27 UTC, merged