Add virus tracker to userapi with /infected endpoint
ct-fiuba/ct-user-api pull request #7
Opened 2021-01-10 13:45 UTC by olifer97

El endpoint de los infectados esta solo protegido por access-token

2021-01-10 15:23 UTC, tomasaccini requested changes
Un lujo Oli! Una consulta que no me acuerdo en qué habíamos quedado despues de tanta discusión y es mas para debatir. Para exponer los códigos infectados ahora estamos pidiendo el access token con el que podríamos saber quien es el usuario que esta mandando los codigos y marcarlo como infectado en nuestra base y nos sirve para las métricas. Pero estrictamente no se si es necesario identificar al usuario infectado, podríamos mandar un genux token para validar que sea un  usuario logueado, marcar las visitas como infectadas y correr el worker que busca posibles infectados de la misma forma, pero lo malo es que terminamos perdiendo métricas de cuántos usuarios hay infectados (xq no sabríamos de los n códigos que recibimos como infectados si son del mismo usuario o de diferentes). no se si me estoy perdiendo algo en el medio @olifer97 @NachoRaik

2021-01-10 15:23 UTC, tomasaccini commented on src/static/swagger.json
> +                          "$ref": "#/components/schemas/Visit"
Idem lo que preguntaba en el PR en ct-virus-tracker, se necesitan todos los parámetros de Visit o unicamente el userGeneratedCode?

2021-01-10 15:23 UTC, tomasaccini commented on test/integration/app.int.test.js
> +          await request(server).post('/infected').set('access-token', token).send({ visits: [visit1, visit2]}).expect(201);
Idem, se necesita todo lo de visits o solo userGeneratedCode?

2021-01-10 20:21 UTC, olifer97 commented
> Un lujo Oli! Una consulta que no me acuerdo en qué habíamos quedado despues de tanta discusión y es mas para debatir. Para exponer los códigos infectados ahora estamos pidiendo el access token con el que podríamos saber quien es el usuario que esta mandando los codigos y marcarlo como infectado en nuestra base y nos sirve para las métricas. Pero estrictamente no se si es necesario identificar al usuario infectado, podríamos mandar un genux token para validar que sea un usuario logueado, marcar las visitas como infectadas y correr el worker que busca posibles infectados de la misma forma, pero lo malo es que terminamos perdiendo métricas de cuántos usuarios hay infectados (xq no sabríamos de los n códigos que recibimos como infectados si son del mismo usuario o de diferentes). no se si me estoy perdiendo algo en el medio @olifer97 @NachoRaik

Igual el endpoint recibe un lista de visitas, si usamos el genuxToken podes identificar que vienen de un mismo usuario tambien, porque vienen de un mismo celular. Si queremos que sea lo mas privado posible habria que hacer que se envie una visita por vez con un genuxToken, pero pense que una vez contagiados no importaba la preservacion.
De todas formas agregar el genuxToken haria que no se QUE usuario es, solo sabria que son del mismo usuario.

2021-01-11 12:55 UTC, tomasaccini commented
> > Un lujo Oli! Una consulta que no me acuerdo en qué habíamos quedado despues de tanta discusión y es mas para debatir. Para exponer los códigos infectados ahora estamos pidiendo el access token con el que podríamos saber quien es el usuario que esta mandando los codigos y marcarlo como infectado en nuestra base y nos sirve para las métricas. Pero estrictamente no se si es necesario identificar al usuario infectado, podríamos mandar un genux token para validar que sea un usuario logueado, marcar las visitas como infectadas y correr el worker que busca posibles infectados de la misma forma, pero lo malo es que terminamos perdiendo métricas de cuántos usuarios hay infectados (xq no sabríamos de los n códigos que recibimos como infectados si son del mismo usuario o de diferentes). no se si me estoy perdiendo algo en el medio @olifer97 @NachoRaik
> 
> Igual el endpoint recibe un lista de visitas, si usamos el genuxToken podes identificar que vienen de un mismo usuario tambien, porque vienen de un mismo celular. Si queremos que sea lo mas privado posible habria que hacer que se envie una visita por vez con un genuxToken, pero pense que una vez contagiados no importaba la preservacion.
> De todas formas agregar el genuxToken haria que no se QUE usuario es, solo sabria que son del mismo usuario.

Claro tenes razón! Entonces en el orden de menor a mayor privacidad quedaría:
1. Mandar con access-token, podemos identificar exactamente qué usuario esta infectado
2. Mandar con genux-token y lista, no podemos identificar qué usuario es pero sabemos que toda la lista viene del mismo usuario. Podríamos sacar metricas aproximadas de cuantos usuarios infectados tenemos según la cantidad de llamadas a este endpoint tenemos. Perdemos métricas de qué usuarios se infectaron, qué movilidad tenían, si estaban vacunados o no, etc
3. Mandar con genux token de a un código por vez (n llamados a la API). Ya no sabríamos ni siquiera cuantos usuarios estan contagiados.

Capaz estaría bueno validar con Mariano e Ignacio qué approach deberíamos tener, pero mergearía este PR y lo laburaría en otro los cambios :)

2021-01-11 12:55 UTC, tomasaccini approved these changes

2021-01-13 22:43 UTC, NachoRaik approved these changes
aprubd

2021-01-14 21:30 UTC, merged